name: Drift News Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "7 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml pytz

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
          COOKIE_VALUE: ${{ secrets.COOKIE_VALUE }}
        run: python news_bot.py
